spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: hh
    
server:
  port: 4100
---  
spring:
  profiles: test
  application:
    name: zz
    
server:
  port: 4101